ctrlc_exit = false
prompt = "build-string (ansi y) (date format '%I:%M:%S') (ansi reset) ' ' (ansi g) (whoami | str trim) '@' (hostname | str trim) (ansi reset) ' ' (ansi r) (pwd | sed 's/\\/home\\/carl/~/') (ansi reset) (ansi g) (if (git rev-parse --is-inside-work-tree 2> /dev/null | str trim) == 'true' { build-string ':' (git branch --show-current | str trim) } { '' }) (ansi reset) ' '"
rm_always_trash = true
startup = [
  "alias vim = nvim",
  "alias ga = git add -A",
  "alias gc = git commit -m",
  "alias gp = git push origin",
  "alias gg = git log --graph --pretty=oneline --abbrev-commit",
  "alias gl = git log --graph --pretty=short",
  "alias gac = git add -A && git commit -m",
  "alias gf = git fetch",
  "alias db = gdb -tui",
  "alias kee = keepassxc-cli open ~/KeePass.kdbx",
  "alias up = paru -Syu",
  "alias add = paru -S",
  "alias del = paru -R",
  "alias search = paru -Ss",
  "alias bat = bat --theme ansi",
  "alias l = ls -la",
  "alias ll = ls -l",
  "alias time = date format '%H:%M:%S'",
  "def lsd [] { ls | where type == Dir }",
  "def lsf [] { ls | where type == File }",
  "pfetch",
  "build-string 'Time is ' (ansi r) (date format '%H:%M:%S') (ansi reset) '\n'"
]

[line_editor]
bell_style = "visible"

[textview]
pager = "bat"
theme = "ansi"
