startup = [
  'alias vim = nvim',
  'alias ga = git add -A',
  'alias gc = git commit -m',
  'alias gp = git push origin',
  'alias gg = git log --graph --pretty=oneline --abbrev-commit',
  'alias gl = git log --graph --pretty=short',
  'alias gac = git add -A && git commit -m',
  'alias gf = git fetch',
  'alias db = gdb -tui',
  'alias kee = keepassxc-cli open ~/KeePass.kdbx',
  'alias up = paru -Syu',
  'alias add = paru -S',
  'alias del = paru -R',
  'alias search = paru -Ss',
  'alias bat = bat --theme ansi',
  'alias l = ls -la',
  'alias ll = ls -l',
  'def lsd [] { ls | where type == Dir }',
  'def lsf [] { ls | where type == File }',
  'pfetch',
]

rm_always_trash = true
ctrlc_exit = false

prompt = "build-string (ansi y) (date format '%I:%M:%S') (ansi reset) ' ' (ansi g) (whoami) '@' (hostname) (ansi reset) ' ' (ansi r) (pwd) (ansi reset) ' '"
pager = "bat"
